#!/usr/bin/env bash
# Build the docs site (dist-pages/) from repo markdown.
#
# Source of truth is the repo's own documentation — README.md and
# AGENTS.md are converted to HTML with pandoc, wrapped in a shared
# stylesheet, and cross-linked. Because the pages are generated from the
# files every contributor already edits, the site cannot drift from the
# repo docs. Add a page by adding "*.md" to DOC_FILES and rebuilding.
#
# Usage: bash scripts/build-pages.sh   (requires pandoc; output: dist-pages/)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/dist-pages"
DOC_FILES=(README.md AGENTS.md)

command -v pandoc >/dev/null 2>&1 || {
  echo "build-pages: pandoc is required (apt-get install pandoc / brew install pandoc)" >&2
  exit 1
}

mkdir -p "$OUT"
cp "$ROOT/.github/pages/style.css" "$OUT/style.css"

COMMIT="${GITHUB_SHA:-$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo 'local')}"
REPO_URL="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}"

for doc in "${DOC_FILES[@]}"; do
  base="$(basename "$doc" .md)"
  title="$base"
  case "$base" in
    README) title="Real Estate Starter" ;;
    AGENTS) title="Agent conventions" ;;
  esac

  pandoc "$ROOT/$doc" \
    --from=gfm \
    --to=html5 \
    --standalone \
    --metadata title="$title" \
    --css=style.css \
    --output="$OUT/${base}.html"

  # Replace the hard-coded pandoc <h1 class="title"> with a header block:
  # site brand + cross-links to the other pages + commit it was built from.
  # sed is used deliberately (small, fixed transform on a pandoc artifact).
  python3 - "$OUT/${base}.html" "$base" "$title" "$COMMIT" "$REPO_URL" <<'PYEOF'
import re
import sys

path, current, title, commit, repo_url = sys.argv[1:6]
html = open(path, encoding="utf-8").read()

links = {
    "README": ('<a href="AGENTS.html">Agent conventions</a>', None),
    "AGENTS": ('<a href="README.html">Real Estate Starter</a>', None),
}[current]
nav = (
    '<nav class="site-nav"><span class="brand">Real Estate Starter</span>'
    f" {links[0]}</nav>"
    f'<p class="built-from">Built from docs at commit <code>{commit}</code>.</p>'
)

# Pandoc emits exactly one <header id="title-block-header"><h1 class="title">…</h1></header>
# when --standalone --metadata title are set. Swap it for our nav.
pattern = re.compile(r'<header id="title-block-header">.*?</header>', re.DOTALL)
if pattern.search(html):
    html = pattern.sub(nav, html, count=1)
else:
    html = nav + html

if repo_url:
    html = html.replace(
        "</body>",
        f'<footer class="repo-link"><a href="{repo_url}">Source repository</a> · '
        f"commit {commit} · generated by scripts/build-pages.sh</footer>\n</body>",
    )

open(path, "w", encoding="utf-8").write(html)
PYEOF
done

# Landing page: copy the README page to index.html so the site root works.
cp "$OUT/README.html" "$OUT/index.html"

ls -la "$OUT"